export const INITIATE_NEGOTIATION_REQUEST = "INITIATE_NEGOTIATION_REQUEST";
export const INITIATE_NEGOTIATION_SUCCESS = "INITIATE_NEGOTIATION_SUCCESS";
export const INITIATE_NEGOTIATION_FAIL = "INITIATE_NEGOTIATION_FAIL";

export const RESPOND_NEGOTIATION_REQUEST = "RESPOND_NEGOTIATION_REQUEST";
export const RESPOND_NEGOTIATION_SUCCESS = "RESPOND_NEGOTIATION_SUCCESS";
export const RESPOND_NEGOTIATION_FAIL = "RESPOND_NEGOTIATION_FAIL";

export const GET_NEGOTIATION_DETAILS_REQUEST = "GET_NEGOTIATION_DETAILS_REQUEST";
export const GET_NEGOTIATION_DETAILS_SUCCESS = "GET_NEGOTIATION_DETAILS_SUCCESS";
export const GET_NEGOTIATION_DETAILS_FAIL = "GET_NEGOTIATION_DETAILS_FAIL";

export const GET_SELLER_NEGOTIATIONS_REQUEST = "GET_SELLER_NEGOTIATIONS_REQUEST";
export const GET_SELLER_NEGOTIATIONS_SUCCESS = "GET_SELLER_NEGOTIATIONS_SUCCESS";
export const GET_SELLER_NEGOTIATIONS_FAIL = "GET_SELLER_NEGOTIATIONS_FAIL";

export const GET_BUYER_NEGOTIATIONS_REQUEST = "GET_BUYER_NEGOTIATIONS_REQUEST";
export const GET_BUYER_NEGOTIATIONS_SUCCESS = "GET_BUYER_NEGOTIATIONS_SUCCESS";
export const GET_BUYER_NEGOTIATIONS_FAIL = "GET_BUYER_NEGOTIATIONS_FAIL";
